const EVENTS = {
    CONNECTION: 'connection',
    CREATE_ROOM: 'CREATE_ROOM',
    ROOMS: 'ROOMS',
    JOINED_ROOMS: 'JOIEND_ROOMS',
    SEND_NEW_MESSAGE: 'SEND_NEW_MESSAGE',
    ROOM_MESSAGE: 'ROOM_MESSAGE',
    JOIN_ROOM: 'JOIN_ROOM',
}

export default EVENTS
